/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    WsButton: typeof import('whimsy-ui/es')['WsButton'];
    WsCell: typeof import('whimsy-ui/es')['WsCell'];
    WsCellGroup: typeof import('whimsy-ui/es')['WsCellGroup'];
    WsCheckbox: typeof import('whimsy-ui/es')['WsCheckbox'];
    WsCheckboxGroup: typeof import('whimsy-ui/es')['WsCheckboxGroup'];
    WsInput: typeof import('whimsy-ui/es')['WsInput'];
    WsRadio: typeof import('whimsy-ui/es')['WsRadio'];
    WsRadioGroup: typeof import('whimsy-ui/es')['WsRadioGroup'];
    WsSwitch: typeof import('whimsy-ui/es')['WsSwitch'];
  }
}
